---
collections:
  - name: awx.awx
  - name: community.hashi_vault
    version: 1.1.3
  - name: community.general
    version: 3.2.0
  - name: community.vmware
    version: 1.10.0
  - name: community.kubernetes
    version: 1.2.1
