---

name: CI

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  podman:
    runs-on: ubuntu-20.04
    name: Podman
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build EE with Podman
        run: |
          tox -e podman
